version: 0.5.1.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration:
  - Debug
before_build:
  - cmd: nuget restore src\Markify.sln -verbosity detailed
build:
  project: src/Markify.sln
  verbosity: minimal
environment:
    COVERALLS_REPO_TOKEN:  
       secure: LzNrIl+p3PFuAPMSM+HwdnXT+edzlFsl/owok+qNPpOiVhkOIk1hQN9ZuPnzULzO
test:
  assemblies:
artifacts:
  - path: '**\*.vsix'
    name: Markify
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/504c1db44c9d942cbbf0
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true