// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Markify.Rendering.T4.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TextTemplating;
    using Markify.Models.Definitions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class TypeTemplate : T4TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 8 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"
 var definition = (TypeDefinition)Session["Content"]; 
            
            #line default
            #line hidden
            this.Write("### **");
            
            #line 9 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetNameWithParameters(definition)));
            
            #line default
            #line hidden
            this.Write("** : ");
            
            #line 9 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetKind(definition)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 10 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetNamespace(definition)));
            
            #line default
            #line hidden
            this.Write("\r\n***\r\n**Accessibility**: ");
            
            #line 12 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(T4Helper.GetAccessModifiers(definition)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 14 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"

	var modifiers = T4Helper.GetModifiers(definition);
	if(!string.IsNullOrWhiteSpace(modifiers))
	{

            
            #line default
            #line hidden
            this.Write("**Specificities**: ");
            
            #line 19 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modifiers));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 21 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"

	}

            
            #line default
            #line hidden
            
            #line 24 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"

	var parents = T4Helper.GetParents(definition);
	if(!string.IsNullOrWhiteSpace(parents))
	{

            
            #line default
            #line hidden
            this.Write("**Implements**: ");
            
            #line 29 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parents));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 31 "C:\Users\jpires\Documents\Markify\src\src\Markify.Rendering.T4\Templates\TypeTemplate.tt"

	}

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
